In [1]:
import pandas as pd #Python library used for working with data sets
import numpy as np #Python library used for working with arrays
import seaborn as sn # library for making statistical graphics in Python
import random as rn 
import matplotlib.pyplot as mat #used to create 2D graphs and plots by using python scripts
from sklearn.model_selection import train_test_split 
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score

In [19]:
df=pd.read_csv('heart.csv') #Read a comma-separated values (csv) file into DataFrame
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

Data Transformation

In [20]:
df.loc[df['sex']==1,'sex']='M' #Replacing 1 with M

/tmp/ipykernel_15027/1182704570.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'M' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['sex']==1,'sex']='M' #Replacing 1 with M

In [21]:
df.loc[df['sex']==0,'sex']='F' #Replacing 0 with F

In [22]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,M,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,M,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,M,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,M,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,F,0,138,294,1,1,106,0,1.9,1,3,2,0

Error CorrectionÂ¶

In [24]:
df[df['ca']==4]

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
52,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
83,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
128,52,M,2,138,223,0,1,169,0,0.0,2,4,2,1
208,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
242,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
290,52,M,2,138,223,0,1,169,0,0.0,2,4,2,1
340,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
348,43,M,0,132,247,1,0,143,1,0.1,1,4,3,0
417,52,M,2,138,223,0,1,169,0,0.0,2,4,2,1
428,43,M,0,132,247,1,0,143,1,0.1,1,4,3,0
465,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
521,58,M,1,125,220,0,1,144,0,0.4,1,4,3,1
597,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
743,58,M,1,125,220,0,1,144,0,0.4,1,4,3,1
749,58,M,1,125,220,0,1,144,0,0.4,1,4,3,1
831,58,M,1,125,220,0,1,144,0,0.4,1,4,3,1
970,38,M,2,138,175,0,1,173,0,0.0,2,4,2,1
993,43,M,0,132,247,1,0,143,1,0.1,1,4,3,0

In [25]:
from sklearn.preprocessing import LabelEncoder
labelencoder=LabelEncoder()
df["sex"]=labelencoder.fit_transform(df["sex"])
df #used to encode categorical variables into numerical labels

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [26]:
df.loc[df['ca']==4,'ca']=np.NaN  #It locates the rows where the value in the 'ca' column is equal to 4 and replaces those values with NaN (Not a Number)

In [27]:
df.isnull().sum()

age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      0
thalach      0
exang        0
oldpeak      0
slope        0
ca          18
thal         0
target       0
dtype: int64

In [10]:
DataFrame1

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2.0,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0.0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0.0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1.0,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0.0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1.0,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1.0,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0.0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1.0,3,0

Model Building

In [11]:
X_train, X_test, y_train, y_test = train_test_split(DataFrame1.iloc[:,:-1], DataFrame1.iloc[:,-1], test_size = 0.3, random_state = 0)

In [12]:
X_train.shape, X_test.shape,y_train.shape

((717, 13), (308, 13), (717,))

In [18]:
gnb = GaussianNB()

In [16]:
gnb.fit(X_train, y_train)
#fitting a Gaussian Naive Bayes (GNB) model on the training data

ValueError: Input X contains NaN.
GaussianNB does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [17]:
y_pred = gnb.predict(X_test)
y_pred

ValueError: Input X contains NaN.
GaussianNB does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))